services:
  - type: web
    name: telegram-movie-bot
    runtime: docker
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: DATABASE_URL
        value: sqlite:///database.db
      - key: MOVIE_CHANNEL_ID
        sync: false
      - key: RENDER_EXTERNAL_URL
        fromValue: true
